"""add working hours change history

Revision ID: 005
Revises: 004
Create Date: 2026-02-08 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_hours_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_hours_changes_effective_from'), 'working_hours_changes', ['effective_from'], unique=False)
    op.create_index(op.f('ix_working_hours_changes_user_id'), 'working_hours_changes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_hours_changes_user_id'), table_name='working_hours_changes')
    op.drop_index(op.f('ix_working_hours_changes_effective_from'), table_name='working_hours_changes')
    op.drop_table('working_hours_changes')
    # ### end Alembic commands ###
