#!/bin/bash
# Install the PraxisZeit git hooks into .git/hooks/
# Idempotent — can be run multiple times.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_SRC="${REPO_ROOT}/scripts/pre-commit-hook.sh"
HOOK_DST="${REPO_ROOT}/.git/hooks/pre-commit"

if [ ! -f "${HOOK_SRC}" ]; then
    echo "error: ${HOOK_SRC} missing" >&2
    exit 1
fi

mkdir -p "$(dirname "${HOOK_DST}")"

# Wrap the source script in a thin launcher so users can still edit
# pre-commit-hook.sh without re-installing.
cat > "${HOOK_DST}" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-git-hooks.sh — edit pre-commit-hook.sh instead.
exec "\$(git rev-parse --show-toplevel)/scripts/pre-commit-hook.sh" "\$@"
EOF

chmod +x "${HOOK_DST}" "${HOOK_SRC}"
echo "Installed pre-commit hook at ${HOOK_DST}"
